# # Isotropic 3D Volume Optimization
#
# This example demonstrates how to set up a 3D topology optimization problem for 
# maximizing the field intensity (volume integral) in a specific region.
#
# We consider an elastic scattering problem (single wavelength) with an isotropic 
# material design.

using DistributedEmitterOpt
using Gridap
using LinearAlgebra

# ## 1. Simulation Setup
# define geometry and mesh params
L, W, H = 100.0, 100.0, 80.0
meshfile = "mesh.msh"

# In a real run, you would generate or load a mesh here.
# For this example, we assume `meshfile` exists or is generated by:
# `genperiodic(geo, meshfile)`

# Build simulation:
# - `foundry_mode=false` enables full 3D design (not 2D extruded)
# - `dir_y=true` sets Dirichlet (PEC) boundaries in Y
sim = build_simulation(meshfile; foundry_mode=false, dir_x=false, dir_y=true)

# ## 2. Physics Definition
# Define the environment (materials) and the wave problem.

# Ag design in fluid (n=1.33)
env = Environment(mat_design="Ag", mat_fluid=1.33)

# Single incident wave: 532nm, normal incidence, y-polarized
inputs = [FieldConfig(532.0; θ=0.0, pol=:y)]

# Empty outputs => Elastic scattering (optimize field at pump frequency)
outputs = FieldConfig[]

pde = MaxwellProblem(env=env, inputs=inputs, outputs=outputs)

# ## 3. Objective Function
# We use the SERS objective with `volume=true` to maximize ∫|E|² dV.
# `αₚ` is set to identity for isotropic enhancement.

αₚ = Matrix{ComplexF64}(I, 3, 3) # Isotropic
objective = SERSObjective(
    αₚ=αₚ,
    volume=true,
    surface=false,
    use_damage_model=false
)

# ## 4. Optimization Controls
# Configure filtering, projection, and regularization.

control = Control(
    use_filter=true,
    R_filter=(15.0, 15.0, 15.0), # Filter radius in nm
    use_dct=false,               # Use Helmholtz filter (better for unstructured 3D)
    use_projection=true,
    β=8.0,                       # Projection steepness
    η=0.5                        # Projection threshold
)

# ## 5. Problem Assembly
# Combine everything into the `OptimizationProblem`.

solver = UmfpackSolver()
prob = OptimizationProblem(pde, objective, sim, solver;
    foundry_mode=false,
    control=control
)

# ## 6. Run Optimization
# Initialize with uniform gray material and run.

init_uniform!(prob, 0.5)

# This would run the optimization loop:
# `optimize!(prob; max_iter=40)`
